/**
 * MCP Tool: generate_build_manifest
 *
 * Final Phase — Build Manifest & Component Report
 *
 * Generates a comprehensive Markdown report documenting every component
 * used on every page of the website. Includes:
 *   - Per-page section breakdown with component listings
 *   - UIverse GitHub URLs for externally-sourced components
 *   - Built-in component library references
 *   - Design token summary
 *   - SEO audit scores (if available)
 *   - Consistency scores (if available)
 *   - Complete project metadata
 *
 * This is the LAST tool in the pipeline — the deliverable report
 * that tells the developer exactly what was used and where it came from.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface PageManifestEntry {
  name: string;
  slug: string;
  sections: string[];
  componentsUsed: string[];
}

export interface UIverseComponentRef {
  name: string;
  category: string;
  sourceUrl: string;
  hasAnimations: boolean;
  animationCount: number;
}

export interface BuiltInComponentRef {
  id: string;
  category: string;
  style: string;
  name: string;
  animationLevel: string;
}

export interface DesignSummary {
  industry: string;
  tone: string;
  theme: string;
  primaryColor: string;
  secondaryColor: string;
  fontHeading: string;
  fontBody: string;
}

export interface AuditScores {
  seoScore?: number;
  seoGrade?: string;
  consistencyScore?: number;
  reviewScore?: number;
  reviewPassed?: boolean;
}

export interface BuildManifestInput {
  projectName: string;
  framework: string;
  pages: PageManifestEntry[];
  uiverseComponents?: UIverseComponentRef[];
  builtInComponents?: BuiltInComponentRef[];
  designSummary?: DesignSummary;
  auditScores?: AuditScores;
  generatedAt?: string;
}

export interface BuildManifestOutput {
  markdown: string;
  summary: string;
  totalComponents: number;
  totalPages: number;
  uiverseCount: number;
  builtInCount: number;
}

// ─── UIverse Category → GitHub Folder Mapping ────────────────────────────────

const GITHUB_BASE = 'https://github.com/uiverse-io/galaxy/blob/main';

const CATEGORY_GITHUB_MAP: Record<string, string> = {
  'button-primary': 'buttons',
  'button-secondary': 'buttons',
  'button': 'buttons',
  'card': 'cards',
  'input': 'inputs',
  'checkbox': 'checkboxes',
  'toggle': 'toggle-switches',
  'radio': 'radio-buttons',
  'loader': 'loaders',
  'badge': 'badges',
  'tooltip': 'tooltips',
  'modal': 'modals',
  'dropdown': 'dropdowns',
  'navigation': 'navigation',
  'form': 'forms',
};

// ─── Built-in Component ID → UIverse Browse URL ─────────────────────────────

function getUIverseBrowseUrl(category: string): string {
  const cat = CATEGORY_GITHUB_MAP[category] || category;
  return `https://uiverse.io/elements?category=${encodeURIComponent(cat)}`;
}

function getGitHubCategoryUrl(category: string): string {
  const folder = CATEGORY_GITHUB_MAP[category] || category;
  return `${GITHUB_BASE}/${folder}`;
}

// ─── Markdown Generation ────────────────────────────────────────────────────

function generateProjectHeader(
  projectName: string,
  framework: string,
  generatedAt: string,
  totalPages: number,
  totalComponents: number
): string {
  return `# ${projectName} — Build Manifest

> **Generated by:** UI Architect MCP Server v3.0 — Built by [FODUU](https://foduu.com)
> **Date:** ${generatedAt}
> **Framework:** ${framework}
> **Pages:** ${totalPages}
> **Total Components Used:** ${totalComponents}

---

`;
}

function generateDesignSection(design: DesignSummary): string {
  return `## Design System

| Property | Value |
|----------|-------|
| **Industry** | ${design.industry} |
| **Tone** | ${design.tone} |
| **Theme** | ${design.theme} |
| **Primary Color** | \`${design.primaryColor}\` |
| **Secondary Color** | \`${design.secondaryColor}\` |
| **Heading Font** | ${design.fontHeading} |
| **Body Font** | ${design.fontBody} |

---

`;
}

function generateAuditSection(scores: AuditScores): string {
  let md = `## Quality Audit Scores

| Audit | Score | Status |
|-------|-------|--------|
`;

  if (scores.seoScore !== undefined) {
    md += `| **SEO Audit** | ${scores.seoScore}/100 | Grade: ${scores.seoGrade || 'N/A'} |\n`;
  }
  if (scores.consistencyScore !== undefined) {
    const status = scores.consistencyScore >= 80 ? '✅ Consistent' : '⚠️ Needs Review';
    md += `| **Design Consistency** | ${scores.consistencyScore}/100 | ${status} |\n`;
  }
  if (scores.reviewScore !== undefined) {
    const status = scores.reviewPassed ? '✅ Passed' : '❌ Failed';
    md += `| **QA Review** | ${scores.reviewScore}/100 | ${status} |\n`;
  }

  md += '\n---\n\n';
  return md;
}

function generatePageSection(
  page: PageManifestEntry,
  builtInComponents: BuiltInComponentRef[],
  uiverseComponents: UIverseComponentRef[],
  pageIndex: number
): string {
  let md = `## Page ${pageIndex + 1}: ${page.name}

**File:** \`${page.slug === 'index' ? 'index.html' : page.slug + '.html'}\`
**Sections:** ${page.sections.length}

### Sections

| # | Section | Components |
|---|---------|------------|
`;

  page.sections.forEach((section, i) => {
    // Find which components this section type typically uses
    const sectionComponents = getSectionComponents(section, page.componentsUsed);
    const componentStr = sectionComponents.length > 0
      ? sectionComponents.map(c => `\`${c}\``).join(', ')
      : '*(standalone)*';
    md += `| ${i + 1} | ${section} | ${componentStr} |\n`;
  });

  md += '\n';

  // Built-in components used on this page
  const pageBuiltIn = builtInComponents.filter(c =>
    page.componentsUsed.some(used =>
      used === c.category || used === c.id || c.category.startsWith(used)
    )
  );

  if (pageBuiltIn.length > 0) {
    md += `### Built-in Components (from 61-component library)\n\n`;
    md += `| Component | Category | Style | Animation | UIverse Browse | GitHub |\n`;
    md += `|-----------|----------|-------|-----------|----------------|--------|\n`;

    pageBuiltIn.forEach(comp => {
      const browseUrl = getUIverseBrowseUrl(comp.category);
      const githubUrl = getGitHubCategoryUrl(comp.category);
      md += `| ${comp.name} | \`${comp.category}\` | ${comp.style} | ${comp.animationLevel} | [Browse](${browseUrl}) | [GitHub](${githubUrl}) |\n`;
    });
    md += '\n';
  }

  // UIverse components used on this page
  const pageUIverse = uiverseComponents.filter(c =>
    page.componentsUsed.some(used =>
      c.category.includes(used) || used.includes(c.category)
    )
  );

  if (pageUIverse.length > 0) {
    md += `### UIverse Components (fetched from GitHub)\n\n`;
    md += `| Component | Category | Animated | Animations | Source |\n`;
    md += `|-----------|----------|----------|------------|--------|\n`;

    pageUIverse.forEach(comp => {
      const animated = comp.hasAnimations ? '✅ Yes' : '❌ No';
      md += `| ${comp.name} | \`${comp.category}\` | ${animated} | ${comp.animationCount} | [View Source](${comp.sourceUrl}) |\n`;
    });
    md += '\n';
  }

  // If no specific component details, list what was used
  if (pageBuiltIn.length === 0 && pageUIverse.length === 0 && page.componentsUsed.length > 0) {
    md += `### Components Used\n\n`;
    page.componentsUsed.forEach(comp => {
      const browseUrl = getUIverseBrowseUrl(comp);
      const githubUrl = getGitHubCategoryUrl(comp);
      md += `- **\`${comp}\`** — [Browse on UIverse](${browseUrl}) | [GitHub Source](${githubUrl})\n`;
    });
    md += '\n';
  }

  md += '---\n\n';
  return md;
}

// ─── Section → Component Mapping (for the manifest table) ───────────────────

const SECTION_COMPONENT_DEFAULTS: Record<string, string[]> = {
  'hero': ['button-primary', 'button-secondary'],
  'features': ['card'],
  'pricing': ['card', 'button-primary', 'button-secondary', 'badge'],
  'testimonials': ['card'],
  'cta': ['button-primary', 'button-secondary'],
  'faq': [],
  'contact-form': ['input', 'button-primary', 'checkbox'],
  'newsletter': ['input', 'button-primary'],
  'footer': [],
  'navigation': ['navigation'],
  'navbar': ['navigation'],
  'product-grid': ['card', 'badge', 'button-primary'],
  'featured-products': ['card', 'badge'],
  'team': ['card'],
  'about': [],
  'stats': ['card'],
  'services': ['card'],
  'clients': [],
  'how-it-works': ['card'],
  'gallery': [],
  'blog': ['card'],
  'portfolio': ['card', 'modal'],
};

function getSectionComponents(sectionType: string, pageComponents: string[]): string[] {
  const defaults = SECTION_COMPONENT_DEFAULTS[sectionType] || [];
  // Return intersection of section defaults and what the page actually uses
  if (defaults.length === 0) return [];
  return defaults.filter(d => pageComponents.some(p => p.includes(d) || d.includes(p)));
}

// ─── Component Summary Section ──────────────────────────────────────────────

function generateComponentSummary(
  builtInComponents: BuiltInComponentRef[],
  uiverseComponents: UIverseComponentRef[]
): string {
  let md = `## All Components Reference\n\n`;

  if (builtInComponents.length > 0) {
    md += `### Built-in Library (${builtInComponents.length} components)\n\n`;
    md += 'These come from the UI Architect\'s curated 61-component library:\n\n';

    // Group by category
    const byCategory = new Map<string, BuiltInComponentRef[]>();
    builtInComponents.forEach(comp => {
      const existing = byCategory.get(comp.category) || [];
      existing.push(comp);
      byCategory.set(comp.category, existing);
    });

    byCategory.forEach((comps, category) => {
      const githubUrl = getGitHubCategoryUrl(category);
      const browseUrl = getUIverseBrowseUrl(category);
      md += `**${category}** — [UIverse](${browseUrl}) | [GitHub](${githubUrl})\n`;
      comps.forEach(comp => {
        md += `  - ${comp.name} (${comp.style}, animation: ${comp.animationLevel})\n`;
      });
      md += '\n';
    });
  }

  if (uiverseComponents.length > 0) {
    md += `### UIverse GitHub Components (${uiverseComponents.length} components)\n\n`;
    md += 'These were fetched from [uiverse-io/galaxy](https://github.com/uiverse-io/galaxy):\n\n';

    uiverseComponents.forEach(comp => {
      const animTag = comp.hasAnimations ? `🎬 ${comp.animationCount} animations` : '📐 Static';
      md += `- **${comp.name}** (\`${comp.category}\`) — ${animTag} — [Source](${comp.sourceUrl})\n`;
    });
    md += '\n';
  }

  md += '---\n\n';
  return md;
}

// ─── Footer ─────────────────────────────────────────────────────────────────

function generateFooter(): string {
  return `## About This Manifest

This build manifest was automatically generated by the **UI Architect MCP Server** — an agency-grade web development pipeline built by [FODUU](https://foduu.com), India's Web Design Company.

### Pipeline Used

| Phase | Tool | Description |
|-------|------|-------------|
| 1 | \`analyze_project\` | Project Manager — scope, pages, requirements |
| 2 | \`plan_architecture\` | System Architect — stack, components, routing |
| 3 | \`design_theme\` | UI/UX Designer — colors, typography, tokens |
| 3.2 | \`explore_components\` | UIverse Explorer — fetch animated components |
| 3.5 | \`select_components\` | Component Selector — adapt to framework |
| 4 | \`generate_background\` | Background Engine — subtle page patterns |
| 5 | \`scaffold_project\` | Scaffolder — project structure & base files |
| 6 | \`generate_full_page\` | Code Generator — complete page code |
| 6.5 | \`seo_audit\` | Marketing Analyst — SEO & marketing checks |
| 6.7 | \`design_consistency_check\` | Consistency Police — multi-page uniformity |
| 7 | \`review_output\` | QA Review — final quality checklist |
| Final | \`generate_build_manifest\` | This report |

### Component Sources

- **Built-in library:** 61 curated components across 13 categories × 5 styles
- **UIverse.io:** 4,300+ open-source components via [GitHub](https://github.com/uiverse-io/galaxy)
- **License:** All UIverse components are [MIT licensed](https://github.com/uiverse-io/galaxy/blob/main/LICENSE)

---

*Generated by UI Architect MCP Server v3.0 — [FODUU](https://foduu.com)*
`;
}

// ─── Main Function ──────────────────────────────────────────────────────────

export function generateBuildManifest(input: BuildManifestInput): BuildManifestOutput {
  const {
    projectName,
    framework,
    pages,
    uiverseComponents = [],
    builtInComponents = [],
    designSummary,
    auditScores,
  } = input;

  const generatedAt = input.generatedAt || new Date().toISOString().split('T')[0];

  // Count totals
  const allUsedComponents = new Set<string>();
  pages.forEach(p => p.componentsUsed.forEach(c => allUsedComponents.add(c)));
  const totalComponents = allUsedComponents.size + uiverseComponents.length;

  // Build the markdown document
  let markdown = '';

  // Header
  markdown += generateProjectHeader(
    projectName,
    framework,
    generatedAt,
    pages.length,
    totalComponents
  );

  // Design summary (if available)
  if (designSummary) {
    markdown += generateDesignSection(designSummary);
  }

  // Audit scores (if available)
  if (auditScores && (
    auditScores.seoScore !== undefined ||
    auditScores.consistencyScore !== undefined ||
    auditScores.reviewScore !== undefined
  )) {
    markdown += generateAuditSection(auditScores);
  }

  // Per-page breakdown
  markdown += `## Pages\n\n`;

  pages.forEach((page, i) => {
    markdown += generatePageSection(page, builtInComponents, uiverseComponents, i);
  });

  // Component reference
  if (builtInComponents.length > 0 || uiverseComponents.length > 0) {
    markdown += generateComponentSummary(builtInComponents, uiverseComponents);
  }

  // Footer
  markdown += generateFooter();

  // Build summary text
  const summary = [
    `Build manifest generated for "${projectName}".`,
    `${pages.length} page(s), ${totalComponents} component(s) documented.`,
    builtInComponents.length > 0 ? `${builtInComponents.length} from built-in library.` : '',
    uiverseComponents.length > 0 ? `${uiverseComponents.length} from UIverse GitHub.` : '',
    `Framework: ${framework}.`,
  ].filter(Boolean).join(' ');

  return {
    markdown,
    summary,
    totalComponents,
    totalPages: pages.length,
    uiverseCount: uiverseComponents.length,
    builtInCount: builtInComponents.length,
  };
}
